import type { Metadata } from "next"
import { LXGW_WenKai_TC } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/navbar"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}
const wenkai = LXGW_WenKai_TC({
	subsets: ["latin"],
	variable: "--font-wenkai-serif",
	weight: ["300", "700"],
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${wenkai.className} antialiased`}>
				<main className='w-full md:w-3/4 mx-auto'>
					<Navbar />
					{children}
				</main>
			</body>
		</html>
	)
}
